// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef PsmUI_h
#define PsmUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include "PsmView.h"
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Counter.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>

class PsmUI {
public:
  PsmUI();
  Fl_Double_Window *mainWindow;
  static Fl_Menu_Item menu_[];
private:
  inline void cb_Open_i(Fl_Menu_*, void*);
  static void cb_Open(Fl_Menu_*, void*);
  inline void cb_Open1_i(Fl_Menu_*, void*);
  static void cb_Open1(Fl_Menu_*, void*);
  inline void cb_Open2_i(Fl_Menu_*, void*);
  static void cb_Open2(Fl_Menu_*, void*);
  inline void cb_Open3_i(Fl_Menu_*, void*);
  static void cb_Open3(Fl_Menu_*, void*);
  inline void cb_Open4_i(Fl_Menu_*, void*);
  static void cb_Open4(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *saveLights;
private:
  inline void cb_saveLights_i(Fl_Menu_*, void*);
  static void cb_saveLights(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *saveNormals;
private:
  inline void cb_saveNormals_i(Fl_Menu_*, void*);
  static void cb_saveNormals(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *saveAlbedos;
private:
  inline void cb_saveAlbedos_i(Fl_Menu_*, void*);
  static void cb_saveAlbedos(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *saveDepths;
private:
  inline void cb_saveDepths_i(Fl_Menu_*, void*);
  static void cb_saveDepths(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *saveVRML;
private:
  inline void cb_Save_i(Fl_Menu_*, void*);
  static void cb_Save(Fl_Menu_*, void*);
  inline void cb_Quit_i(Fl_Menu_*, void*);
  static void cb_Quit(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *solveLights;
private:
  inline void cb_solveLights_i(Fl_Menu_*, void*);
  static void cb_solveLights(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *solveNormals;
private:
  inline void cb_solveNormals_i(Fl_Menu_*, void*);
  static void cb_solveNormals(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *solveAlbedos;
private:
  inline void cb_solveAlbedos_i(Fl_Menu_*, void*);
  static void cb_solveAlbedos(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *solveDepths;
private:
  inline void cb_solveDepths_i(Fl_Menu_*, void*);
  static void cb_solveDepths(Fl_Menu_*, void*);
public:
  PsmView *view;
  Fl_Tabs *tabs;
private:
  inline void cb_tabs_i(Fl_Tabs*, void*);
  static void cb_tabs(Fl_Tabs*, void*);
public:
  Fl_Group *sourcesTab;
private:
  inline void cb_sourcesTab_i(Fl_Group*, void*);
  static void cb_sourcesTab(Fl_Group*, void*);
public:
  Fl_Counter *imageNum;
private:
  inline void cb_imageNum_i(Fl_Counter*, void*);
  static void cb_imageNum(Fl_Counter*, void*);
public:
  Fl_Check_Button *showMask;
private:
  inline void cb_showMask_i(Fl_Check_Button*, void*);
  static void cb_showMask(Fl_Check_Button*, void*);
public:
  Fl_Group *normalsTab;
private:
  inline void cb_normalsTab_i(Fl_Group*, void*);
  static void cb_normalsTab(Fl_Group*, void*);
public:
  Fl_Choice *normalsMode;
private:
  inline void cb_normalsMode_i(Fl_Choice*, void*);
  static void cb_normalsMode(Fl_Choice*, void*);
  static Fl_Menu_Item menu_normalsMode[];
public:
  Fl_Counter *needleSpacing;
private:
  inline void cb_needleSpacing_i(Fl_Counter*, void*);
  static void cb_needleSpacing(Fl_Counter*, void*);
public:
  Fl_Group *albedoTab;
private:
  inline void cb_albedoTab_i(Fl_Group*, void*);
  static void cb_albedoTab(Fl_Group*, void*);
public:
  Fl_Group *surfaceTab;
private:
  inline void cb_surfaceTab_i(Fl_Group*, void*);
  static void cb_surfaceTab(Fl_Group*, void*);
public:
  Fl_Check_Button *useAlbedos;
private:
  inline void cb_useAlbedos_i(Fl_Check_Button*, void*);
  static void cb_useAlbedos(Fl_Check_Button*, void*);
public:
  Fl_Output *status;
  void go();
};
#endif
